use hw2m;
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','1','Intro to DBMS');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','10','Principles of Network Security');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','11','Basic Electrical Science');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','12','Analog Circuits');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','13','Embedded Hardware Design');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','14','Signals & Systems');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','15','Wireless Communications');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','16','Communication Theory');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','17','Communication Networks');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','18','Error Correcting Codes');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','19','Computational Electromagnetics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','2','Machine Learning');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(2,'Electrical Science','20','Analog & mixed signal design');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','21','Building materials & construction');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','22','Mechanics of Solids');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','23','Structural Analysis');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','24','Strength of materials');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','25','Water Resource Engg.');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','26','Design of concrete Structures');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','27','Soil Mechanics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','28','Environmental Science');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','29','Design of steel Structures');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','3','Deep Learning');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(4,'Building Science','30','Transportation Engg.');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','31','Digital Logic Design');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','32','Engineering Electronics 1');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','33','Basic Electronic Circuits');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','34','Linear Electronic Circuits');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','35','Digital Integrated Circuits');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','36','Semiconductor Processing');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','37','Lasers & Photonics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','38','Microelectronics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','39','Bioelectrics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','4','Analysis of Algorithms 1');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(3,'Electronics','40','Optical Communications');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','41','Linear Algebra');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','42','Calculus 1');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','43','Calculus 2');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','44','Probability Theory & Statistics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','45','Differential Equations');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','46','Number Theory in Cryptography');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','47','Abstract Algebra');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','48','Mathematics 1');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','49','Complex Numbers');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','5','Analysis of Algorithms 2');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(6,'Mathematics','50','Fourier & Laplace Transforms');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','51','General Chemistry for Engineers');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','52','University Physics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','53','Electromagnetic Field Theory');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','54','Intro to Quantum Optics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','55','Quantum Mechanics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','56','Semiconductor Physics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','57','Electricity, Magnetism, and Waves');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','58','Mathematical Methods for Physics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','59','Thermodynamics and Kinetic Theory');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','6','Advanced Machine Learning');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(5,'Natural Sciences','60','Foundations of Modern Physics');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','61','History of Black Magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','62','Chemistry for black magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','63','Computational Black Magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','64','Black Magic lab 1');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','65','Practical Applications of black magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','66','Acing interviews with black magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','67','Case study - How google search uses black magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','68','Ethical Concerns associated with black magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','69','Gray Hat and White hat practitioners');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','7','Bayesian Models');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(7,'Black Magic','70','Solving NP-Hard problems with black magic');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','8','Data Structures');
INSERT INTO Offered_by(`DeptID`,`DeptName`,`CourseID`,`CourseName`) VALUES(1,'Computer Science','9','Graphics & Animation');
