use hw2m;
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('6','Advanced Machine Learning','1','Intro to DBMS');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('1','Intro to DBMS','9','Graphics & Animation');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('6','Advanced Machine Learning','4','Analysis of Algorithms 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('6','Advanced Machine Learning','9','Graphics & Animation');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('5','Analysis of Algorithms 2','2','Machine Learning');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('2','Machine Learning','4','Analysis of Algorithms 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('3','Deep Learning','6','Advanced Machine Learning');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('6','Advanced Machine Learning','2','Machine Learning');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('14','Signals & Systems','11','Basic Electrical Science');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('11','Basic Electrical Science','13','Embedded Hardware Design');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('18','Error Correcting Codes','16','Communication Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('16','Communication Theory','17','Communication Networks');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('12','Analog Circuits','17','Communication Networks');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('13','Embedded Hardware Design','19','Computational Electromagnetics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('19','Computational Electromagnetics','17','Communication Networks');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('13','Embedded Hardware Design','14','Signals & Systems');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('14','Signals & Systems','15','Wireless Communications');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('22','Mechanics of Solids','21','Building materials & construction');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('21','Building materials & construction','28','Environmental Science');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('21','Building materials & construction','27','Soil Mechanics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('27','Soil Mechanics','28','Environmental Science');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('29','Design of steel Structures','22','Mechanics of Solids');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('22','Mechanics of Solids','25','Water Resource Engg.');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('23','Structural Analysis','21','Building materials & construction');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('21','Building materials & construction','26','Design of concrete Structures');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('39','Bioelectrics','38','Microelectronics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('38','Microelectronics','35','Digital Integrated Circuits');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('33','Basic Electronic Circuits','37','Lasers & Photonics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('35','Digital Integrated Circuits','39','Bioelectrics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('39','Bioelectrics','32','Engineering Electronics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('32','Engineering Electronics 1','37','Lasers & Photonics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('33','Basic Electronic Circuits','34','Linear Electronic Circuits');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('34','Linear Electronic Circuits','31','Digital Logic Design');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('43','Calculus 2','48','Mathematics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('48','Mathematics 1','47','Abstract Algebra');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('47','Abstract Algebra','41','Linear Algebra');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('47','Abstract Algebra','42','Calculus 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('47','Abstract Algebra','49','Complex Numbers');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('49','Complex Numbers','43','Calculus 2');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('46','Number Theory in Cryptography','44','Probability Theory & Statistics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('44','Probability Theory & Statistics','42','Calculus 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('57','Electricity, Magnetism, and Waves','59','Thermodynamics and Kinetic Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('58','Mathematical Methods for Physics','53','Electromagnetic Field Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('53','Electromagnetic Field Theory','59','Thermodynamics and Kinetic Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('52','University Physics','57','Electricity, Magnetism, and Waves');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('57','Electricity, Magnetism, and Waves','53','Electromagnetic Field Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('52','University Physics','51','General Chemistry for Engineers');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('69','Gray Hat and White hat practitioners','63','Computational Black Magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('63','Computational Black Magic','68','Ethical Concerns associated with black magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('69','Gray Hat and White hat practitioners','65','Practical Applications of black magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('65','Practical Applications of black magic','63','Computational Black Magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('68','Ethical Concerns associated with black magic','64','Black Magic lab 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('63','Computational Black Magic','61','History of Black Magic');
