INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('1','Intro to DBMS',1,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('10','Principles of Network Security',1,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('10','Principles of Network Security',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('11','Basic Electrical Science',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('12','Analog Circuits',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('13','Embedded Hardware Design',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('13','Embedded Hardware Design',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('14','Signals & Systems',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('14','Signals & Systems',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('15','Wireless Communications',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('16','Communication Theory',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('17','Communication Networks',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('18','Error Correcting Codes',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('19','Computational Electromagnetics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('2','Machine Learning',1,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('2','Machine Learning',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('20','Analog & mixed signal design',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('21','Building materials & construction',3,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('22','Mechanics of Solids',2,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('22','Mechanics of Solids',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('23','Structural Analysis',1,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('24','Strength of materials',2,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('24','Strength of materials',3,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('25','Water Resource Engg.',1,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('25','Water Resource Engg.',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('26','Design of concrete Structures',1,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('26','Design of concrete Structures',2,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('27','Soil Mechanics',3,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('27','Soil Mechanics',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('28','Environmental Science',2,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('29','Design of steel Structures',3,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('29','Design of steel Structures',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('3','Deep Learning',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('30','Transportation Engg.',2,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('30','Transportation Engg.',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('31','Digital Logic Design',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('31','Digital Logic Design',3,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('32','Engineering Electronics 1',2,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('33','Basic Electronic Circuits',2,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('33','Basic Electronic Circuits',3,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('34','Linear Electronic Circuits',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('34','Linear Electronic Circuits',3,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('34','Linear Electronic Circuits',4,'9936696','Paxton','Spencer');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('35','Digital Integrated Circuits',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('35','Digital Integrated Circuits',2,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('36','Semiconductor Processing',3,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('37','Lasers & Photonics',3,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('38','Microelectronics',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('38','Microelectronics',3,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('38','Microelectronics',4,'9936696','Paxton','Spencer');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('39','Bioelectrics',2,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('4','Analysis of Algorithms 1',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('40','Optical Communications',2,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('41','Linear Algebra',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('42','Calculus 1',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('43','Calculus 2',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('43','Calculus 2',2,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('44','Probability Theory & Statistics',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('44','Probability Theory & Statistics',2,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('45','Differential Equations',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('46','Number Theory in Cryptography',2,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('47','Abstract Algebra',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('48','Mathematics 1',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('49','Complex Numbers',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('5','Analysis of Algorithms 2',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('50','Fourier & Laplace Transforms',2,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('51','General Chemistry for Engineers',1,'5121001','Robert','OKon');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('52','University Physics',2,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('52','University Physics',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('53','Electromagnetic Field Theory',1,'5121001','Robert','OKon');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('53','Electromagnetic Field Theory',2,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('53','Electromagnetic Field Theory',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('54','Intro to Quantum Optics',1,'5121001','Robert','OKon');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('54','Intro to Quantum Optics',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('55','Quantum Mechanics',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('56','Semiconductor Physics',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('56','Semiconductor Physics',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('57','Electricity, Magnetism, and Waves',2,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('58','Mathematical Methods for Physics',2,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('59','Thermodynamics and Kinetic Theory',1,'5121001','Robert','OKon');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('59','Thermodynamics and Kinetic Theory',2,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('59','Thermodynamics and Kinetic Theory',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('6','Advanced Machine Learning',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('60','Foundations of Modern Physics',2,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('60','Foundations of Modern Physics',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('60','Foundations of Modern Physics',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('61','History of Black Magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('61','History of Black Magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('62','Chemistry for black magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('63','Computational Black Magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('63','Computational Black Magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('64','Black Magic lab 1',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('64','Black Magic lab 1',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('65','Practical Applications of black magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('65','Practical Applications of black magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('66','Acing interviews with black magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('66','Acing interviews with black magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('67','Case study - How google search uses black magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('67','Case study - How google search uses black magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('68','Ethical Concerns associated with black magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('69','Gray Hat and White hat practitioners',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('7','Bayesian Models',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('70','Solving NP-Hard problems with black magic',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('8','Data Structures',1,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('8','Data Structures',2,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('9','Graphics & Animation',1,'4773645','Carmen','Yundt');
