use hw2m;
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1046236','Emmanuelle','Champlin','26','Design of concrete Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1046236','Emmanuelle','Champlin','7','Bayesian Models',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('108305','Derick','Herzog','58','Mathematical Methods for Physics',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('108305','Derick','Herzog','38','Microelectronics',3);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('108305','Derick','Herzog','35','Digital Integrated Circuits',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1122938','Kaleb','Wunsch','31','Digital Logic Design',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1122938','Kaleb','Wunsch','33','Basic Electronic Circuits',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('1122938','Kaleb','Wunsch','34','Linear Electronic Circuits',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('1122938','Kaleb','Wunsch','37','Lasers & Photonics',3,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('119385','Kelsi','Bahringer','30','Transportation Engg.',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('119385','Kelsi','Bahringer','36','Semiconductor Processing',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1226675','Guiseppe','Trantow','41','Linear Algebra',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1226675','Guiseppe','Trantow','44','Probability Theory & Statistics',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('1226675','Guiseppe','Trantow','42','Calculus 1',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1456827','Monserrate','Donnelly','28','Environmental Science',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1456827','Monserrate','Donnelly','65','Practical Applications of black magic',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('1456827','Monserrate','Donnelly','63','Computational Black Magic',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1483094','Mckayla','Marks','34','Linear Electronic Circuits',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1483094','Mckayla','Marks','63','Computational Black Magic',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('1483094','Mckayla','Marks','68','Ethical Concerns associated with black magic',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('1483094','Mckayla','Marks','61','History of Black Magic',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1830038','Briana','Pouros','30','Transportation Engg.',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('1830038','Briana','Pouros','25','Water Resource Engg.',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('187456','Khalil','Swift','39','Bioelectrics',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('187456','Khalil','Swift','34','Linear Electronic Circuits',4);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('187456','Khalil','Swift','31','Digital Logic Design',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('187456','Khalil','Swift','68','Ethical Concerns associated with black magic',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('187456','Khalil','Swift','61','History of Black Magic',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2003939','Simone','Lubowitz','47','Abstract Algebra',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2003939','Simone','Lubowitz','51','General Chemistry for Engineers',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2166740','Garnet','Bode','1','Intro to DBMS',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2166740','Garnet','Bode','39','Bioelectrics',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2166740','Garnet','Bode','68','Ethical Concerns associated with black magic',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2166740','Garnet','Bode','31','Digital Logic Design',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2166740','Garnet','Bode','32','Engineering Electronics 1',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2166740','Garnet','Bode','61','History of Black Magic',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2166740','Garnet','Bode','38','Microelectronics',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2214635','Fannie','Marquardt','1','Intro to DBMS',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2214635','Fannie','Marquardt','57','Electricity, Magnetism, and Waves',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2214635','Fannie','Marquardt','53','Electromagnetic Field Theory',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2214635','Fannie','Marquardt','59','Thermodynamics and Kinetic Theory',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2243042','Tina','Hudson','37','Lasers & Photonics',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2243042','Tina','Hudson','50','Fourier & Laplace Transforms',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2323349','Roxane','Treutel','66','Acing interviews with black magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2323349','Roxane','Treutel','32','Engineering Electronics 1',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2323349','Roxane','Treutel','37','Lasers & Photonics',3,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2348464','Lou','Mayer','70','Solving NP-Hard problems with black magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2348464','Lou','Mayer','68','Ethical Concerns associated with black magic',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2348464','Lou','Mayer','64','Black Magic lab 1',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2399880','Esperanza','Fahey','6','Advanced Machine Learning',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2399880','Esperanza','Fahey','54','Intro to Quantum Optics',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('249892','Melyna','Rolfson','59','Thermodynamics and Kinetic Theory',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('249892','Melyna','Rolfson','52','University Physics',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('249892','Melyna','Rolfson','51','General Chemistry for Engineers',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('249892','Melyna','Rolfson','57','Electricity, Magnetism, and Waves',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2519995','Tiara','Mitchell','19','Computational Electromagnetics',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2519995','Tiara','Mitchell','11','Basic Electrical Science',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2519995','Tiara','Mitchell','13','Embedded Hardware Design',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2675321','Julie','Bergstrom','36','Semiconductor Processing',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2675321','Julie','Bergstrom','12','Analog Circuits',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2675321','Julie','Bergstrom','17','Communication Networks',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2689948','Viva','Douglas','14','Signals & Systems',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2689948','Viva','Douglas','70','Solving NP-Hard problems with black magic',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2689948','Viva','Douglas','64','Black Magic lab 1',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2724427','Abdullah','Gerlach','10','Principles of Network Security',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2724427','Abdullah','Gerlach','51','General Chemistry for Engineers',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2843927','Madisen','Grimes','19','Computational Electromagnetics',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2843927','Madisen','Grimes','12','Analog Circuits',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('2843927','Madisen','Grimes','17','Communication Networks',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2952864','Jorge','Cummerata','52','University Physics',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('2952864','Jorge','Cummerata','55','Quantum Mechanics',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3058253','Angeline','Predovic','10','Principles of Network Security',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3058253','Angeline','Predovic','7','Bayesian Models',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3110237','Ruthie','Goldner','46','Number Theory in Cryptography',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3110237','Ruthie','Goldner','65','Practical Applications of black magic',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3110237','Ruthie','Goldner','63','Computational Black Magic',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3211500','Eileen','Rowe','48','Mathematics 1',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3211500','Eileen','Rowe','39','Bioelectrics',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3211500','Eileen','Rowe','68','Ethical Concerns associated with black magic',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3211500','Eileen','Rowe','31','Digital Logic Design',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3211500','Eileen','Rowe','32','Engineering Electronics 1',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3211500','Eileen','Rowe','61','History of Black Magic',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3211500','Eileen','Rowe','38','Microelectronics',3,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3218640','Jermey','Willms','8','Data Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3218640','Jermey','Willms','7','Bayesian Models',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3353909','Carson','Huel','41','Linear Algebra',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3353909','Carson','Huel','46','Number Theory in Cryptography',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3353909','Carson','Huel','44','Probability Theory & Statistics',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3353909','Carson','Huel','63','Computational Black Magic',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3363152','Queen','Sawayn','29','Design of steel Structures',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3363152','Queen','Sawayn','28','Environmental Science',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3363152','Queen','Sawayn','63','Computational Black Magic',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3487297','Stacy','McLaughlin','27','Soil Mechanics',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3487297','Stacy','McLaughlin','41','Linear Algebra',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3487297','Stacy','McLaughlin','44','Probability Theory & Statistics',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3487297','Stacy','McLaughlin','42','Calculus 1',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3487297','Stacy','McLaughlin','63','Computational Black Magic',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('350835','Aditya','Stokes','70','Solving NP-Hard problems with black magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('350835','Aditya','Stokes','63','Computational Black Magic',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('350835','Aditya','Stokes','68','Ethical Concerns associated with black magic',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('350835','Aditya','Stokes','61','History of Black Magic',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3635025','Raheem','Rogahn','20','Analog & mixed signal design',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3635025','Raheem','Rogahn','13','Embedded Hardware Design',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3635025','Raheem','Rogahn','19','Computational Electromagnetics',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3635025','Raheem','Rogahn','14','Signals & Systems',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3842048','Carlie','Kerluke','22','Mechanics of Solids',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3842048','Carlie','Kerluke','50','Fourier & Laplace Transforms',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3894755','Willow','Kovacek','40','Optical Communications',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3894755','Willow','Kovacek','38','Microelectronics',3);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3894755','Willow','Kovacek','35','Digital Integrated Circuits',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3901455','Athena','Conroy','23','Structural Analysis',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('3901455','Athena','Conroy','52','University Physics',3);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3901455','Athena','Conroy','51','General Chemistry for Engineers',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('3901455','Athena','Conroy','57','Electricity, Magnetism, and Waves',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4038360','Angus','Welch','34','Linear Electronic Circuits',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4038360','Angus','Welch','38','Microelectronics',3);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4038360','Angus','Welch','35','Digital Integrated Circuits',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4120205','Michele','Sauer','46','Number Theory in Cryptography',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4120205','Michele','Sauer','62','Chemistry for black magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4124507','Gerard','Hahn','26','Design of concrete Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4124507','Gerard','Hahn','28','Environmental Science',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4124507','Gerard','Hahn','63','Computational Black Magic',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4146108','Brant','Rippin','30','Transportation Engg.',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4146108','Brant','Rippin','14','Signals & Systems',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4146108','Brant','Rippin','64','Black Magic lab 1',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4146108','Brant','Rippin','11','Basic Electrical Science',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4146108','Brant','Rippin','15','Wireless Communications',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4291180','Cynthia','Sanford','25','Water Resource Engg.',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('4291180','Cynthia','Sanford','70','Solving NP-Hard problems with black magic',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4291180','Cynthia','Sanford','64','Black Magic lab 1',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4291180','Cynthia','Sanford','68','Ethical Concerns associated with black magic',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('4291180','Cynthia','Sanford','61','History of Black Magic',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5194621','Carrie','Ullrich','64','Black Magic lab 1',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5194621','Carrie','Ullrich','65','Practical Applications of black magic',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5194621','Carrie','Ullrich','63','Computational Black Magic',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5209857','Lue','Jenkins','29','Design of steel Structures',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5209857','Lue','Jenkins','23','Structural Analysis',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5209857','Lue','Jenkins','51','General Chemistry for Engineers',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5209857','Lue','Jenkins','57','Electricity, Magnetism, and Waves',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5209857','Lue','Jenkins','21','Building materials & construction',3,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5279488','Janice','Waters','47','Abstract Algebra',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5279488','Janice','Waters','11','Basic Electrical Science',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5279488','Janice','Waters','13','Embedded Hardware Design',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5286705','Aida','Lemke','38','Microelectronics',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5286705','Aida','Lemke','68','Ethical Concerns associated with black magic',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5286705','Aida','Lemke','64','Black Magic lab 1',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5357196','Bernardo','Ledner','9','Graphics & Animation',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5357196','Bernardo','Ledner','38','Microelectronics',4);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5357196','Bernardo','Ledner','64','Black Magic lab 1',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5357196','Bernardo','Ledner','35','Digital Integrated Circuits',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5544611','Davonte','Bartoletti','26','Design of concrete Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5544611','Davonte','Bartoletti','40','Optical Communications',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5544611','Davonte','Bartoletti','35','Digital Integrated Circuits',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('577128','Howell','VonRueden','25','Water Resource Engg.',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('577128','Howell','VonRueden','33','Basic Electronic Circuits',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('577128','Howell','VonRueden','34','Linear Electronic Circuits',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('577128','Howell','VonRueden','37','Lasers & Photonics',3,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5878911','Vada','Dare','3','Deep Learning',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('5878911','Vada','Dare','5','Analysis of Algorithms 2',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('5878911','Vada','Dare','2','Machine Learning',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6127813','Carmine','Muller','40','Optical Communications',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6127813','Carmine','Muller','34','Linear Electronic Circuits',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6127813','Carmine','Muller','31','Digital Logic Design',3,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6127813','Carmine','Muller','68','Ethical Concerns associated with black magic',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6127813','Carmine','Muller','61','History of Black Magic',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6127813','Carmine','Muller','35','Digital Integrated Circuits',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6168118','Kasandra','Jacobi','46','Number Theory in Cryptography',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6168118','Kasandra','Jacobi','10','Principles of Network Security',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6230579','Mittie','Medhurst','55','Quantum Mechanics',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6230579','Mittie','Medhurst','13','Embedded Hardware Design',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6230579','Mittie','Medhurst','19','Computational Electromagnetics',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6230579','Mittie','Medhurst','14','Signals & Systems',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6312014','Wiley','Daniel','19','Computational Electromagnetics',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6312014','Wiley','Daniel','9','Graphics & Animation',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6312014','Wiley','Daniel','64','Black Magic lab 1',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6312014','Wiley','Daniel','35','Digital Integrated Circuits',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6390411','Teagan','Morar','11','Basic Electrical Science',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6390411','Teagan','Morar','20','Analog & mixed signal design',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6390411','Teagan','Morar','19','Computational Electromagnetics',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6390411','Teagan','Morar','14','Signals & Systems',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('63991','Kobe','Baumbach','25','Water Resource Engg.',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('63991','Kobe','Baumbach','14','Signals & Systems',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('63991','Kobe','Baumbach','64','Black Magic lab 1',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('63991','Kobe','Baumbach','11','Basic Electrical Science',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('63991','Kobe','Baumbach','15','Wireless Communications',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6426769','Haley','Kunde','70','Solving NP-Hard problems with black magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6426769','Haley','Kunde','8','Data Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6488326','Rene','Wintheiser','21','Building materials & construction',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6488326','Rene','Wintheiser','30','Transportation Engg.',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6488326','Rene','Wintheiser','64','Black Magic lab 1',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6488326','Rene','Wintheiser','11','Basic Electrical Science',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6488326','Rene','Wintheiser','15','Wireless Communications',2,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6518392','Pietro','Cole','65','Practical Applications of black magic',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6518392','Pietro','Cole','68','Ethical Concerns associated with black magic',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6518392','Pietro','Cole','64','Black Magic lab 1',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6547859','Bruce','Thompson','13','Embedded Hardware Design',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6547859','Bruce','Thompson','15','Wireless Communications',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6573643','Kitty','Blanda','19','Computational Electromagnetics',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6573643','Kitty','Blanda','14','Signals & Systems',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6573643','Kitty','Blanda','64','Black Magic lab 1',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6573643','Kitty','Blanda','11','Basic Electrical Science',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6573643','Kitty','Blanda','15','Wireless Communications',2,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6581486','Milford','Fay','69','Gray Hat and White hat practitioners',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6581486','Milford','Fay','26','Design of concrete Structures',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6581486','Milford','Fay','63','Computational Black Magic',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6581486','Milford','Fay','35','Digital Integrated Circuits',1,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6605236','Magnus','Dibbert','26','Design of concrete Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('6605236','Magnus','Dibbert','27','Soil Mechanics',4);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6605236','Magnus','Dibbert','28','Environmental Science',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6605236','Magnus','Dibbert','44','Probability Theory & Statistics',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6605236','Magnus','Dibbert','42','Calculus 1',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('6605236','Magnus','Dibbert','63','Computational Black Magic',1,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7048760','Hector','Bauch','11','Basic Electrical Science',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7048760','Hector','Bauch','17','Communication Networks',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7097159','Marianna','Lebsack','54','Intro to Quantum Optics',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7097159','Marianna','Lebsack','56','Semiconductor Physics',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7157161','Hayley','Homenick','60','Foundations of Modern Physics',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7157161','Hayley','Homenick','58','Mathematical Methods for Physics',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7157161','Hayley','Homenick','53','Electromagnetic Field Theory',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7157161','Hayley','Homenick','35','Digital Integrated Circuits',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7297006','Shane','Metz','59','Thermodynamics and Kinetic Theory',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7297006','Shane','Metz','64','Black Magic lab 1',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7297006','Shane','Metz','63','Computational Black Magic',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7700462','Jessika','Terry','32','Engineering Electronics 1',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7700462','Jessika','Terry','38','Microelectronics',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7700462','Jessika','Terry','64','Black Magic lab 1',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7700462','Jessika','Terry','35','Digital Integrated Circuits',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('786717','Effie','Quitzon','16','Communication Theory',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('786717','Effie','Quitzon','23','Structural Analysis',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('786717','Effie','Quitzon','51','General Chemistry for Engineers',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('786717','Effie','Quitzon','57','Electricity, Magnetism, and Waves',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('786717','Effie','Quitzon','21','Building materials & construction',3,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7868325','Berta','Auer','27','Soil Mechanics',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7868325','Berta','Auer','47','Abstract Algebra',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7868325','Berta','Auer','13','Embedded Hardware Design',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7868325','Berta','Auer','49','Complex Numbers',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7868325','Berta','Auer','42','Calculus 1',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('7868325','Berta','Auer','41','Linear Algebra',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7891745','Allan','Lang','53','Electromagnetic Field Theory',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('7891745','Allan','Lang','10','Principles of Network Security',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8005225','Alek','Streich','26','Design of concrete Structures',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8005225','Alek','Streich','27','Soil Mechanics',3);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','63','Computational Black Magic',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','28','Environmental Science',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','44','Probability Theory & Statistics',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','42','Calculus 1',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','41','Linear Algebra',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','13','Embedded Hardware Design',1,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8005225','Alek','Streich','49','Complex Numbers',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8006202','Reymundo','Glover','42','Calculus 1',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8006202','Reymundo','Glover','43','Calculus 2',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8006202','Reymundo','Glover','48','Mathematics 1',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8006814','Nichole','Tillman','55','Quantum Mechanics',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8006814','Nichole','Tillman','58','Mathematical Methods for Physics',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8006814','Nichole','Tillman','53','Electromagnetic Field Theory',3,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8006814','Nichole','Tillman','35','Digital Integrated Circuits',2,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('810465','Jordane','Watsica','63','Computational Black Magic',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('810465','Jordane','Watsica','43','Calculus 2',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('810465','Jordane','Watsica','48','Mathematics 1',1,'B');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('834354','Ova','Upton','41','Linear Algebra',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('834354','Ova','Upton','46','Number Theory in Cryptography',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('834354','Ova','Upton','44','Probability Theory & Statistics',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('834354','Ova','Upton','63','Computational Black Magic',1,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8348742','Zackery','Paucek','61','History of Black Magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8348742','Zackery','Paucek','62','Chemistry for black magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8392592','Evert','Friesen','53','Electromagnetic Field Theory',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8392592','Evert','Friesen','26','Design of concrete Structures',2);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','63','Computational Black Magic',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','28','Environmental Science',2,'B');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','44','Probability Theory & Statistics',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','42','Calculus 1',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','35','Digital Integrated Circuits',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','41','Linear Algebra',1,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','13','Embedded Hardware Design',2,'A');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8392592','Evert','Friesen','49','Complex Numbers',1,'C');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8813103','Soledad','Dietrich','3','Deep Learning',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8813103','Soledad','Dietrich','4','Analysis of Algorithms 1',2);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8933058','Rocky','Hills','22','Mechanics of Solids',4);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('8933058','Rocky','Hills','23','Structural Analysis',1);
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8933058','Rocky','Hills','51','General Chemistry for Engineers',1,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8933058','Rocky','Hills','57','Electricity, Magnetism, and Waves',2,'C');
INSERT INTO Has_completed(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`,`Grade`) VALUES('8933058','Rocky','Hills','21','Building materials & construction',3,'A');
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('9003709','Wilburn','Kirlin','1','Intro to DBMS',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('9003709','Wilburn','Kirlin','37','Lasers & Photonics',3);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('9064924','Telly','Moore','61','History of Black Magic',1);
INSERT INTO Has_enrolled_in(`StudentID`,`StudentFName`,`StudentLName`,`CourseID`,`CourseName`,`SectionNumber`) VALUES('9064924','Telly','Moore','15','Wireless Communications',2);
