use hw2;
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','4383597','Dominic','Jones','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(7,'Black Magic','4383597','Dominic','Jones','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(4,'Building Science','4387189','Velva','Greenfelder','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','4416925','Petra','Windler','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(2,'Electrical Science','4452493','Herman','Monahan','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(3,'Electronics','4498251','Meredith','Kling','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(4,'Building Science','4498251','Meredith','Kling','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(2,'Electrical Science','4547617','Elmore','Gislason','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(3,'Electronics','4547617','Elmore','Gislason','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(5,'Natural Sciences','4547617','Elmore','Gislason','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(7,'Black Magic','4701832','Mina','Crona','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','4773645','Carmen','Yundt','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(3,'Electronics','4773645','Carmen','Yundt','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(2,'Electrical Science','5121001','Robert','OKon','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(4,'Building Science','5147071','Tomas','Pollich','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(6,'Mathematics','9211397','Marcelle','Bruen','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(2,'Electrical Science','9334741','Alisha','Jacobs','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','9367129','Paula','Nikolaus','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(6,'Mathematics','9367129','Paula','Nikolaus','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','9429138','Zoila','Maggio','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(6,'Mathematics','9429138','Zoila','Maggio','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(3,'Electronics','9460352','Toby','Ratke','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(7,'Black Magic','9460352','Toby','Ratke','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','9538638','Rodolfo','Stracke','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(7,'Black Magic','9538638','Rodolfo','Stracke','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(2,'Electrical Science','974054','Zoie','Mohr','Adjunt Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(6,'Mathematics','9744898','Hailee','Walsh','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(2,'Electrical Science','978516','Katelynn','Wisozk','Assistant Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(4,'Building Science','978516','Katelynn','Wisozk','Senior Professor');
INSERT INTO Serves_in(`DeptID`,`DeptName`,`FacultyID`,`FacultyFName`,`FacultyLName`,`Designation`) VALUES(1,'Computer Science','9936696','Paxton','Spencer','Adjunt Professor');
