use hw2m;
UPDATE Faculty SET DeptID=1,DeptName='Computer Science' WHERE FacultyID=4773645;
UPDATE Faculty SET DeptID=1,DeptName='Computer Science' WHERE FacultyID=9744898;
UPDATE Faculty SET DeptID=2,DeptName='Electrical Science' WHERE FacultyID=9367129;
UPDATE Faculty SET DeptID=2,DeptName='Electrical Science' WHERE FacultyID=4547617;
UPDATE Faculty SET DeptID=3,DeptName='Electronics' WHERE FacultyID=9936696;
UPDATE Faculty SET DeptID=3,DeptName='Electronics' WHERE FacultyID=9460352;
UPDATE Faculty SET DeptID=3,DeptName='Electronics' WHERE FacultyID=974054;
UPDATE Faculty SET DeptID=3,DeptName='Electronics' WHERE FacultyID=4387189;
UPDATE Faculty SET DeptID=4,DeptName='Building Science' WHERE FacultyID=9211397;
UPDATE Faculty SET DeptID=4,DeptName='Building Science' WHERE FacultyID=4416925;
UPDATE Faculty SET DeptID=4,DeptName='Building Science' WHERE FacultyID=978516;
UPDATE Faculty SET DeptID=4,DeptName='Building Science' WHERE FacultyID=4452493;
UPDATE Faculty SET DeptID=5,DeptName='Natural Sciences' WHERE FacultyID=9334741;
UPDATE Faculty SET DeptID=5,DeptName='Natural Sciences' WHERE FacultyID=5121001;
UPDATE Faculty SET DeptID=5,DeptName='Natural Sciences' WHERE FacultyID=9429138;
UPDATE Faculty SET DeptID=5,DeptName='Natural Sciences' WHERE FacultyID=9538638;
UPDATE Faculty SET DeptID=6,DeptName='Mathematics' WHERE FacultyID=4383597;
UPDATE Faculty SET DeptID=6,DeptName='Mathematics' WHERE FacultyID=5147071;
UPDATE Faculty SET DeptID=7,DeptName='Black Magic' WHERE FacultyID=4498251;
UPDATE Faculty SET DeptID=7,DeptName='Black Magic' WHERE FacultyID=4701832;
