use hw2m;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=2399880;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=9003709;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=2214635;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=2724427;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=5357196;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=3058253;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=8813103;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=5878911;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=3218640;
UPDATE Student SET DeptID=1,DeptName='Computer Science' WHERE StudentID=2166740;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=2689948;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=3635025;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=6547859;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=2519995;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=7048760;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=6573643;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=786717;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=6390411;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=6312014;
UPDATE Student SET DeptID=2,DeptName='Electrical Science' WHERE StudentID=2843927;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=6127813;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=1122938;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=3894755;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=7700462;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=2243042;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=187456;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=1483094;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=2675321;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=5286705;
UPDATE Student SET DeptID=3,DeptName='Electronics' WHERE StudentID=4038360;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=3842048;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=5209857;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=6605236;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=1046236;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=8005225;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=577128;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=7868325;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=4124507;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=8933058;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=3363152;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=4291180;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=3901455;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=63991;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=6488326;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=1456827;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=4146108;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=119385;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=3487297;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=1830038;
UPDATE Student SET DeptID=4,DeptName='Building Science' WHERE StudentID=5544611;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=7157161;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=7297006;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=7097159;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=8392592;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=7891745;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=8006814;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=2952864;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=249892;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=108305;
UPDATE Student SET DeptID=5,DeptName='Natural Sciences' WHERE StudentID=6230579;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=8006202;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=3110237;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=3353909;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=6168118;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=5279488;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=834354;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=4120205;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=1226675;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=2003939;
UPDATE Student SET DeptID=6,DeptName='Mathematics' WHERE StudentID=3211500;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=810465;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=6581486;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=8348742;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=5194621;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=6426769;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=6518392;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=9064924;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=350835;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=2323349;
UPDATE Student SET DeptID=7,DeptName='Black Magic' WHERE StudentID=2348464;
