use hw2m;
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('1','Intro to DBMS',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('1','Intro to DBMS',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('1','Intro to DBMS',5,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('10','Principles of Network Security',6,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('11','Basic Electrical Science',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('11','Basic Electrical Science',4,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('11','Basic Electrical Science',5,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('11','Basic Electrical Science',6,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('12','Analog',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('12','Analog',3,'5121001','Robert','OKon');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('12','Analog',6,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('13','Embedded Hardware Design',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('13','Embedded Hardware Design',3,'5121001','Robert','OKon');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('13','Embedded Hardware Design',5,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('14','Signals & Systems',5,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('15','Wireless Communications',1,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('15','Wireless Communications',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('15','Wireless Communications',5,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('15','Wireless Communications',6,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('16','Communication Theory',6,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('17','Communication Networks',6,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('18','Error Correcting Codes',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('19','Computational Electromagnetics',1,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('19','Computational Electromagnetics',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('19','Computational Electromagnetics',5,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('2','Machine Learning',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('2','Machine Learning',2,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('2','Machine Learning',4,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('2','Machine Learning',5,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('20','Analog & mixed signal design',1,'4452493','Herman','Monahan');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('20','Analog & mixed signal design',4,'9334741','Alisha','Jacobs');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('20','Analog & mixed signal design',5,'974054','Zoie','Mohr');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('20','Analog & mixed signal design',6,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('21','Building materials & construction',2,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('21','Building materials & construction',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('22','Mechanics of Solids',2,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('22','Mechanics of Solids',3,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('23','Structural Analysis',3,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('24','Strength of materials',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('24','Strength of materials',2,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('24','Strength of materials',3,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('25','Water Resource Engg.',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('26','Design of concrete Structures',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('26','Design of concrete Structures',3,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('27','Soil Mechanics',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('27','Soil Mechanics',3,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('27','Soil Mechanics',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('28','Environmental Science',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('28','Environmental Science',2,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('28','Environmental Science',3,'5147071','Tomas','Pollich');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('29','Design of steel Structures',1,'4387189','Velva','Greenfelder');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('29','Design of steel Structures',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('3','Deep Learning',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('30','Transportation Engg.',2,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('30','Transportation Engg.',4,'978516','Katelynn','Wisozk');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('31','Digital Logic Design',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('32','Engineering Electronics 1',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('33','Basic Electronic Circuits',4,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('34','Linear Electronic Circuits',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('34','Linear Electronic Circuits',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('34','Linear Electronic Circuits',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('35','Digital Integrated Circuits',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('35','Digital Integrated Circuits',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('35','Digital Integrated Circuits',4,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('36','Semiconductor Processing',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('36','Semiconductor Processing',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('36','Semiconductor Processing',4,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('37','Lasers & Photonics',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('37','Lasers & Photonics',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('37','Lasers & Photonics',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('38','Microelectronics',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('38','Microelectronics',2,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('38','Microelectronics',4,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('39','Bioelectrics',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('39','Bioelectrics',4,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('4','Analysis of Algorithms 1',5,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('40','Optical Communications',1,'4498251','Meredith','Kling');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('40','Optical Communications',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('40','Optical Communications',4,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('41','Linear Algebra',4,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('42','Calculus 1',1,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('42','Calculus 1',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('42','Calculus 1',4,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('43','Calculus 2',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('44','Probability Theory & Statistics',1,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('44','Probability Theory & Statistics',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('45','Differential Equations',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('45','Differential Equations',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('45','Differential Equations',4,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('46','Number Theory in Cryptography',1,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('46','Number Theory in Cryptography',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('46','Number Theory in Cryptography',4,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('47','Abstract Algebra',1,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('47','Abstract Algebra',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('48','Mathematics 1',1,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('48','Mathematics 1',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('48','Mathematics 1',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('49','Complex Numbers',1,'9211397','Marcelle','Bruen');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('49','Complex Numbers',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('49','Complex Numbers',3,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('5','Analysis of Algorithms 2',2,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('5','Analysis of Algorithms 2',4,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('5','Analysis of Algorithms 2',5,'9429138','Zoila','Maggio');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('50','Fourier & Laplace Transforms',2,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('50','Fourier & Laplace Transforms',4,'9744898','Hailee','Walsh');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('51','General Chemistry for Engineers',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('52','University Physics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('53','Electromagnetic Field Theory',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('54','Intro to Quantum Optics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('55','Quantum Mechanics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('56','Semiconductor Physics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('57','Electricity, Magnetism, and Waves',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('58','Mathematical Methods for Physics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('59','Thermodynamics and Kinetic Theory',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('6','Advanced Machine Learning',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('6','Advanced Machine Learning',2,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('6','Advanced Machine Learning',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('6','Advanced Machine Learning',4,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('60','Foundations of Modern Physics',1,'4547617','Elmore','Gislason');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('61','History of Black Magic',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('61','History of Black Magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('61','History of Black Magic',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('62','Chemistry for black magic',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('62','Chemistry for black magic',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('63','Computational Black Magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('64','Black Magic lab 1',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('64','Black Magic lab 1',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('64','Black Magic lab 1',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('65','Practical Applications of black magic',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('66','Acing interviews with black magic',2,'4701832','Mina','Crona');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('66','Acing interviews with black magic',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('66','Acing interviews with black magic',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('67','Case study - How google search uses black magic',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('67','Case study - How google search uses black magic',4,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('68','Ethical Concerns associated with black magic',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('69','Gray Hat and White hat practitioners',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('7','Bayesian Models',1,'4383597','Dominic','Jones');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('7','Bayesian Models',2,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('7','Bayesian Models',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('7','Bayesian Models',4,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('70','Solving NP-Hard problems with black magic',3,'9460352','Toby','Ratke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('8','Data Structures',4,'9367129','Paula','Nikolaus');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('9','Graphics & Animation',2,'4416925','Petra','Windler');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('9','Graphics & Animation',3,'4773645','Carmen','Yundt');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('9','Graphics & Animation',6,'9538638','Rodolfo','Stracke');
INSERT INTO Sections(`CourseID`,`CourseName`,`SectionNumber`,`FacultyID`,`InstructorFName`,`InstructorLName`) VALUES('9','Graphics & Animation',7,'9936696','Paxton','Spencer');
