use hw2m;
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('1','Intro to DBMS','CS-0001');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('2','Machine Learning','CS-0002');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('3','Deep Learning','CS-0003');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('4','Analysis of Algorithms 1','CS-0004');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('5','Analysis of Algorithms 2','CS-0005');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('6','Advanced Machine Learning','CS-0006');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('7','Bayesian Models','CS-0007');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('8','Data Structures','CS-0008');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('9','Graphics & Animation','CS-0009');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('10','Principles of Network Security','CS-0010');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('11','Basic Electrical Science','ES-1001');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('12','Analog Circuits','ES-1002');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('13','Embedded Hardware Design','ES-1003');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('14','Signals & Systems','ES-1004');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('15','Wireless Communications','ES-1005');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('16','Communication Theory','ES-1006');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('17','Communication Networks','ES-1007');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('18','Error Correcting Codes','ES-1008');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('19','Computational Electromagnetics','ES-1009');
INSERT INTO Course(`CourseID`,`FullName`,`CourseCode`) VALUES('20','Analog & mixed signal design','ES-1010');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('21','Building materials & construction','BS-2001');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('22','Mechanics of Solids','BS-2002');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('23','Structural Analysis','BS-2003');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('24','Strength of materials','BS-2004');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('25','Water Resource Engg.','BS-2005');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('26','Design of concrete Structures','BS-2006');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('27','Soil Mechanics','BS-2007');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('28','Environmental Science','BS-2008');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('29','Design of steel Structures','BS-2009');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('30','Transportation Engg.','BS-2010');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('31','Digital Logic Design','EL-3001');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('32','Engineering Electronics 1','EL-3002');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('33','Basic Electronic Circuits','EL-3003');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('34','Linear Electronic Circuits','EL-3004');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('35','Digital Integrated Circuits','EL-3005');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('36','Semiconductor Processing','EL-3006');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('37','Lasers & Photonics','EL-3007');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('38','Microelectronics','EL-3008');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('39','Bioelectrics','EL-3009');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('40','Optical Communications','EL-3010');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('41','Linear Algebra','MT-4001');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('42','Calculus 1','MT-4002');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('43','Calculus 2','MT-4003');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('44','Probability Theory & Statistics','MT-4004');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('45','Differential Equations','MT-4005');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('46','Number Theory in Cryptography','MT-4006');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('47','Abstract Algebra','MT-4007');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('48','Mathematics 1','MT-4008');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('49','Complex Numbers','MT-4009');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('50','Fourier & Laplace Transforms','MT-4010');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('51','General Chemistry for Engineers','NS-5001');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('52','University Physics','NS-5002');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('53','Electromagnetic Field Theory','NS-5003');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('54','Intro to Quantum Optics','NS-5004');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('55','Quantum Mechanics','NS-5005');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('56','Semiconductor Physics','NS-5006');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('57','Electricity, Magnetism, and Waves','NS-5007');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('58','Mathematical Methods for Physics','NS-5008');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('59','Thermodynamics and Kinetic Theory','NS-5009');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('60','Foundations of Modern Physics','NS-5010');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('61','History of Black Magic','BM-6001');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('62','Chemistry for black magic','BM-6002');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('63','Computational Black Magic','BM-6003');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('64','Black Magic lab 1','BM-6004');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('65','Practical Applications of black magic','BM-6005');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('66','Acing interviews with black magic','BM-6006');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('67','Case study - How google search uses black magic','BM-6007');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('68','Ethical Concerns associated with black magic','BM-6008');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('69','Gray Hat and White hat practitioners','BM-6009');
INSERT INTO Course(`CourseID`, `FullName`, `CourseCode`) VALUES('70','Solving NP-Hard problems with black magic','BM-6010');
