use hw2m;
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('1','Intro to DBMS','3','Deep Learning');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('3','Deep Learning','9','Graphics & Animation');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('2','Machine Learning','4','Analysis of Algorithms 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('2','Machine Learning','1','Intro to DBMS');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('2','Machine Learning','7','Bayesian Models');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('18','Error Correcting Codes','17','Communication Networks');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('17','Communication Networks','16','Communication Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('11','Basic Electrical Science','14','Signals & Systems');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('14','Signals & Systems','17','Communication Networks');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('14','Signals & Systems','18','Error Correcting Codes');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('18','Error Correcting Codes','13','Embedded Hardware Design');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('16','Communication Theory','19','Computational Electromagnetics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('19','Computational Electromagnetics','12','Analog');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('22','Mechanics of Solids','21','Building materials & construction');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('21','Building materials & construction','24','Strength of materials');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('28','Environmental Science','22','Mechanics of Solids');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('27','Soil Mechanics','24','Strength of materials');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('24','Strength of materials','28','Environmental Science');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('21','Building materials & construction','29','Design of steel Structures');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('29','Design of steel Structures','27','Soil Mechanics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('21','Building materials & construction','28','Environmental Science');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('38','Microelectronics','35','Digital Integrated Circuits');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('35','Digital Integrated Circuits','32','Engineering Electronics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('34','Linear Electronic Circuits','31','Digital Logic Design');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('31','Digital Logic Design','38','Microelectronics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('35','Digital Integrated Circuits','33','Basic Electronic Circuits');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('33','Basic Electronic Circuits','32','Engineering Electronics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('39','Bioelectrics','38','Microelectronics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('38','Microelectronics','36','Semiconductor Processing');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('39','Bioelectrics','33','Basic Electronic Circuits');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('43','Calculus 2','42','Calculus 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('42','Calculus 1','48','Mathematics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('45','Differential Equations','47','Abstract Algebra');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('43','Calculus 2','48','Mathematics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('48','Mathematics 1','44','Probability Theory & Statistics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('41','Linear Algebra','43','Calculus 2');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('41','Linear Algebra','47','Abstract Algebra');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('47','Abstract Algebra','48','Mathematics 1');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('58','Mathematical Methods for Physics','57','Electricity, Magnetism, and Waves');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('53','Electromagnetic Field Theory','59','Thermodynamics and Kinetic Theory');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('59','Thermodynamics and Kinetic Theory','55','Quantum Mechanics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('54','Intro to Quantum Optics','56','Semiconductor Physics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('56','Semiconductor Physics','55','Quantum Mechanics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('58','Mathematical Methods for Physics','55','Quantum Mechanics');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('69','Gray Hat and White hat practitioners','68','Ethical Concerns associated with black magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('68','Ethical Concerns associated with black magic','65','Practical Applications of black magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('63','Computational Black Magic','67','Case study - How google search uses black magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('67','Case study - How google search uses black magic','65','Practical Applications of black magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('67','Case study - How google search uses black magic','69','Gray Hat and White hat practitioners');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('64','Black Magic lab 1','61','History of Black Magic');
INSERT INTO Prerequisite(`CourseID`,`CourseName`,`PrereqCourseID`,`PrereqCourseName`) VALUES('61','History of Black Magic','63','Computational Black Magic');
