CREATE TABLE `Student` (
  `UNI` varchar(12) NOT NULL,
  `year` int(11) NOT NULL,
  PRIMARY KEY (`UNI`),
  CONSTRAINT `fk_table1_uni` FOREIGN KEY (`UNI`) REFERENCES `Person` (`UNI`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;